version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: php-apache.dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    environment: # TODO There are reports that host.docker.internal does not work on Linux. This should be confirmed/debunked.
      XDEBUG_CONFIG: remote_host=host.docker.internal

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database

volumes:
  mysql_data: {}