version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: php-apache.dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - sc2ladderwebhost_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database

volumes:
  sc2ladderwebhost_mysql_data: {}